# Generated by Django 6.1.1 on 2026-09-27 08:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_order_number_sequence'),
        ('products', '0002_product_product_stock_gte_zero'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_item_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0.01'))), name='order_item_price_gte_zero'),
        ),
    ]
