repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.8
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy (type-check)
        entry: mypy
        language: system
        types_or: [python, pyi]

      - id: pytest
        name: pytest (docker test-suite)
        entry: docker compose --env-file .env.test -f docker-compose.test.yaml up --build --exit-code-from tests
        language: system
        pass_filenames: false
        stages: [pre-push]