services:
  db:
    container_name: "luxshop-db"
    image: postgres:17-alpine
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      .env.dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      retries: 10

  backend:
      build:
        context: .
        dockerfile: ./Dockerfile
      env_file: .env.dev
      environment:
        - DJANGO_SETTINGS_MODULE=config.settings.dev
      ports:
        - "${HOST_PORT:-8008}:8000"
      volumes:
        - .:/app
        - /app/.venv
        - media:/app/media
      depends_on:
        db:
          condition: service_healthy

volumes:
  pgdata:
  media: