# Generated by Django 6.1.1 on 2026-10-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_preset',
            field=models.CharField(blank=True, choices=[('avatar1', 'Avatar 1'), ('avatar2', 'Avatar 2'), ('avatar3', 'Avatar 3'), ('avatar4', 'Avatar 4'), ('avatar5', 'Avatar 5'), ('avatar6', 'Avatar 6'), ('avatar7', 'Avatar 7'), ('avatar8', 'Avatar 8'), ('avatar9', 'Avatar 9'), ('avatar10', 'Avatar 10')], max_length=16, verbose_name='avatar preset'),
        ),
    ]
