# Generated by Django 6.1.1 on 2026-09-27 07:51

from django.db import migrations


def create_and_sync_sequence(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    Order = apps.get_model("orders", "Order")
    table_name = Order._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("CREATE SEQUENCE IF NOT EXISTS order_number_seq START WITH 100001;")

        cursor.execute(f"""
            SELECT COALESCE(
                MAX(
                    CASE 
                        WHEN order_number ~ '^[0-9]+$' THEN order_number::INTEGER 
                        ELSE 0 
                    END
                ), 
                100000
            ) FROM {table_name};
        """)
        max_val = cursor.fetchone()[0]
        start_val = max(max_val, 100000)

        cursor.execute(f"SELECT setval('order_number_seq', {start_val});")


def drop_sequence(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("DROP SEQUENCE IF EXISTS order_number_seq;")


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_and_sync_sequence, reverse_code=drop_sequence),
    ]
